### PR TITLE
Upgraded project to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by jasminsehic**

### CODE REVIEW

**Comment by ethomson** [comment]
Hi @jasminsehic!  Thanks for the work and the PR.

I'm afraid that I'm not maintaining this project anymore.  Would you like to take it over?

**Comment by jasminsehic** [comment]
Hey @ethomson I can maintain it no probs.

**Comment by ethomson** [comment]
Cool.  It looks like I can transfer this repository to you - however, [you can't have your fork of this repository in your account](https://help.github.com/en/articles/transferring-a-repository).  Can you delete your fork (https://github.com/jasminsehic/infinity.net), and then I'll transfer this repository to you?

That means that redirects and such will work from here to there, and the rest of the forks will remain pointing to your repository.

(Be sure to make a backup of any branches that you've pushed to your fork of this repository before you delete anything!)

**Comment by jasminsehic** [comment]
I've just deleted my fork and kept backup of branches. 
I can see that Travis CI and probably AppVeyor builds are failing. If that something you can transfer or should I create new projects for them?

**Comment by ethomson** [comment]
OK, I initiated the transfer!

As for CI, I think it might be worth setting up new ones entirely.  (And I'm obligated to suggest https://azure.com/pipelines 😀 )

**Comment by jasminsehic** [comment]
OK just accepted it. I will give Pipelines a go too.

**Comment by jasminsehic** [comment]
@ethomson can you please add me as an owner for the nuget package on nuget.org? My username is jasminsehic

**Comment by ethomson** [comment]
> can you please add me as an owner for the nuget package on nuget.org? My username is jasminsehic

I tried adding you, and it told me that it was successful, but it also gave me an internal server error.  So let me know if you got it!

**Comment by jasminsehic** [comment]
Got it! All good.

**Comment by jasminsehic** [comment]
@ethomson question about Microsoft.TeamFoundationServer.Client. Would you say this supersedes the Infinity.NET library now? I personally find Microsoft.TeamFoundationServer.Client very difficult to follow and documentation isn't great and Infinity.NET has always been simpler. Just wanted to get your opinion on whether it is worth potentially building something on top of Microsoft.TeamFoundationServer.Client instead of direct REST api calls.

**Pull request closed without merging**
